/**
 * Which relation lines a node panel shows for a species, derived from the graph
 * model's own grammar.
 *
 * Derived, not restated. `VALID_EDGE_SEMANTICS` is the table `validateBundle()`
 * and the canvas connect dialog (`EdgeTypeDialog`) already read, and a second
 * hand-written list of what may attach to what is a second chance for the panel
 * and the canvas to disagree about the model. What this module adds on top of
 * the grammar is only what the grammar does not say: what to call each
 * direction, what order to show them in, and which edge type the panel does not
 * author at all.
 *
 * Deliberately React-free and provider-free — the panel resolves ids to nodes,
 * this decides what to resolve.
 */

import {
  SPECIES_IDS,
  VALID_EDGE_SEMANTICS,
  type EdgeTypeId,
  type SpeciesId,
} from "@arkaik/schema";
import type { Edge } from "@/lib/data/types";

/** Which way the edge runs, relative to the node whose panel is open. */
export type RelationDirection = "out" | "in";

export type RelationLineId = `${EdgeTypeId}:${RelationDirection}`;

export interface RelationLineSpec {
  readonly id: RelationLineId;
  readonly edgeType: EdgeTypeId;
  readonly direction: RelationDirection;
  /** The heading. See {@link RELATION_LINE_LABELS}. */
  readonly label: string;
  /** What a new counterpart may be, from the grammar. Never empty. */
  readonly counterpartSpecies: readonly SpeciesId[];
}

/**
 * What each direction of each edge type is called on a panel.
 *
 * All mechanical but one: `covers:in` is **Acceptances**, not "Covered by".
 * That is the heading the section has carried since it existed and the word a
 * reader of a view panel is looking for, and it is written down here rather
 * than special-cased at the call site so that one table answers "what is this
 * line called".
 */
export const RELATION_LINE_LABELS: Record<EdgeTypeId, { out: string; in: string }> = {
  composes: { out: "Composes", in: "Composed by" },
  calls: { out: "Calls", in: "Called by" },
  displays: { out: "Displays", in: "Displayed by" },
  queries: { out: "Queries", in: "Queried by" },
  covers: { out: "Covers", in: "Acceptances" },
  supersedes: { out: "Supersedes", in: "Superseded by" },
  generates: { out: "Generated acceptances", in: "Generated by" },
  impacts: { out: "Impacts", in: "Impacted by" },
};

/**
 * Edge types no panel line covers.
 *
 * `composes` only. A `composes` edge is half of a relationship whose other half
 * is `metadata.playlist.entries`; writing one without the other leaves the
 * flow's order to `journey-graph`'s "append the missing children" fallback,
 * which is a silent reorder nobody asked for. `PlaylistEditor` owns that write,
 * and the panel's read of it — the Invocation section — stays read-only for the
 * same reason.
 */
export const PANEL_EXCLUDED_EDGE_TYPES: readonly EdgeTypeId[] = ["composes"];

/**
 * The order lines appear in, as an explicit list.
 *
 * Not `EDGE_TYPE_IDS`' order: sorting by that enum's index would silently
 * reorder every panel the day an edge type is appended to it. Covers lines
 * first (the per-species spec order), then cross-layer, then decision links.
 */
export const RELATION_LINE_ORDER: readonly RelationLineId[] = [
  "covers:out",
  "covers:in",
  "calls:out",
  "calls:in",
  "displays:out",
  "displays:in",
  "queries:out",
  "queries:in",
  "supersedes:out",
  "supersedes:in",
  "generates:out",
  "generates:in",
  "impacts:out",
  "impacts:in",
];

// `RELATION_LINE_ORDER` is a plain array, not a `Record`, so TypeScript cannot
// catch an omitted line id the way it catches a missing `RELATION_LINE_LABELS`
// entry. A rank lookup with a safe fallback keeps that omission from being a
// silent layout regression: an unordered line ranked last lands at the bottom
// of the panel, visible and harmless, rather than ranked first (`indexOf`'s
// -1) at the top, where it would look like the line the panel cares about
// most.
const RELATION_LINE_RANK: ReadonlyMap<RelationLineId, number> = new Map(
  RELATION_LINE_ORDER.map((id, index) => [id, index]),
);
function rankOf(id: RelationLineId): number {
  return RELATION_LINE_RANK.get(id) ?? Number.MAX_SAFE_INTEGER;
}

function buildRelationLines(species: SpeciesId): readonly RelationLineSpec[] {
  const lines: RelationLineSpec[] = [];

  for (const [edgeType, pairs] of Object.entries(VALID_EDGE_SEMANTICS) as [
    EdgeTypeId,
    ReadonlyArray<[SpeciesId, SpeciesId]>,
  ][]) {
    if (PANEL_EXCLUDED_EDGE_TYPES.includes(edgeType)) continue;

    for (const direction of ["out", "in"] as const) {
      const counterpartSpecies = [
        ...new Set(
          pairs
            .filter(([source, target]) => (direction === "out" ? source : target) === species)
            .map(([source, target]) => (direction === "out" ? target : source)),
        ),
      ];
      if (counterpartSpecies.length === 0) continue;

      // The spec itself is frozen, not just its `counterpartSpecies` array:
      // this object lives in the module-level table below and is handed out
      // to every caller, so a mutation through one caller must not leak into
      // the next.
      lines.push(
        Object.freeze({
          id: `${edgeType}:${direction}` as RelationLineId,
          edgeType,
          direction,
          label: RELATION_LINE_LABELS[edgeType][direction],
          counterpartSpecies: Object.freeze(counterpartSpecies),
        }),
      );
    }
  }

  lines.sort((a, b) => rankOf(a.id) - rankOf(b.id));
  return Object.freeze(lines);
}

/**
 * The per-species table, built once at module load rather than per call.
 *
 * Parts 2–4 call `relationLinesFor` inside render; a fresh array of fresh
 * objects on every call would make any `useMemo`/`React.memo` keyed on it dead
 * weight. Six species — the whole table is cheap to build once. Frozen at
 * every level — the outer record, each species' line array, each spec object,
 * and each spec's `counterpartSpecies` array — so a mutation through one
 * caller cannot leak into the next; a shallow freeze here would have left the
 * spec objects themselves mutable even though the arrays holding them are not.
 */
const RELATION_LINES_BY_SPECIES: Readonly<Record<SpeciesId, readonly RelationLineSpec[]>> =
  Object.freeze(
    Object.fromEntries(SPECIES_IDS.map((species) => [species, buildRelationLines(species)])) as Record<
      SpeciesId,
      readonly RelationLineSpec[]
    >,
  );

// A shared constant rather than `?? []`, which would mint a fresh array on
// every call for an unknown species — harmless for what this module does with
// it, but a needless allocation and a value that is not referentially stable
// across calls.
const NO_LINES: readonly RelationLineSpec[] = Object.freeze([]);

/** The relation lines a node of this species has, in {@link RELATION_LINE_ORDER}. */
export function relationLinesFor(species: SpeciesId): readonly RelationLineSpec[] {
  return RELATION_LINES_BY_SPECIES[species] ?? NO_LINES;
}

/** One row of a line: the counterpart's id, and the edge that put it there. */
export interface RelationRow {
  edgeId: string;
  counterpartId: string;
}

/**
 * The edges filling one line for one node, in edge order.
 *
 * Ids, not nodes: the caller resolves them and drops what this snapshot cannot
 * see, the same way `coveredAnchorsOf` does — a row naming an id the panel
 * cannot show is worse than no row.
 *
 * De-duplicated on the counterpart, keeping the FIRST edge — both its position
 * and its identity. `e-{source}-{target}` makes a duplicate pair impossible to
 * mint through the app, but a hand-edited or half-synced bundle can carry two
 * edges with the same endpoints and different ids; the first is the canonical
 * `e-{source}-{target}` id the rest of the app also names, and a stray from a
 * hand-edit or a half-sync is the one dropped.
 *
 * A self-loop (an endpoint calling itself, a decision superseding itself) is
 * not filtered: the grammar admits `api-endpoint → api-endpoint` and
 * `decision → decision` deliberately, and a node this true of is real graph
 * data the user put there. It renders as one row under the node's outbound
 * line and one row under its inbound line — the same edge read from both
 * directions, same as any other edge between two distinct nodes.
 */
export function relationRows(
  nodeId: string,
  line: RelationLineSpec,
  edges: readonly Edge[],
): RelationRow[] {
  const rows = edges
    .filter((edge) => edge.edge_type === line.edgeType)
    .filter((edge) => (line.direction === "out" ? edge.source_id : edge.target_id) === nodeId)
    .map((edge) => ({
      edgeId: edge.id,
      counterpartId: line.direction === "out" ? edge.target_id : edge.source_id,
    }));

  const seen = new Map<string, RelationRow>();
  for (const row of rows) {
    if (!seen.has(row.counterpartId)) seen.set(row.counterpartId, row);
  }
  return [...seen.values()];
}
