/**
 * Which relation lines a node panel shows for a species, derived from the graph
 * model's own grammar.
 *
 * Derived, not restated. `VALID_EDGE_SEMANTICS` is the table `validateBundle()`
 * and the canvas connect dialog (`EdgeTypeDialog`) already read, and a second
 * hand-written list of what may attach to what is a second chance for the panel
 * and the canvas to disagree about the model. What this module adds on top of
 * the grammar is only what the grammar does not say: what to call each
 * direction, what order to show them in, and which edge type the panel does not
 * author at all.
 *
 * Deliberately React-free and provider-free — the panel resolves ids to nodes,
 * this decides what to resolve.
 */

import {
  VALID_EDGE_SEMANTICS,
  type EdgeTypeId,
  type SpeciesId,
} from "@arkaik/schema";
import type { Edge } from "@/lib/data/types";

/** Which way the edge runs, relative to the node whose panel is open. */
export type RelationDirection = "out" | "in";

export type RelationLineId = `${EdgeTypeId}:${RelationDirection}`;

export interface RelationLineSpec {
  id: RelationLineId;
  edgeType: EdgeTypeId;
  direction: RelationDirection;
  /** The heading. See {@link RELATION_LINE_LABELS}. */
  label: string;
  /** What a new counterpart may be, from the grammar. Never empty. */
  counterpartSpecies: SpeciesId[];
}

/**
 * What each direction of each edge type is called on a panel.
 *
 * All mechanical but one: `covers:in` is **Acceptances**, not "Covered by".
 * That is the heading the section has carried since it existed and the word a
 * reader of a view panel is looking for, and it is written down here rather
 * than special-cased at the call site so that one table answers "what is this
 * line called".
 */
export const RELATION_LINE_LABELS: Record<EdgeTypeId, { out: string; in: string }> = {
  composes: { out: "Composes", in: "Composed by" },
  calls: { out: "Calls", in: "Called by" },
  displays: { out: "Displays", in: "Displayed by" },
  queries: { out: "Queries", in: "Queried by" },
  covers: { out: "Covers", in: "Acceptances" },
  supersedes: { out: "Supersedes", in: "Superseded by" },
  generates: { out: "Generated acceptances", in: "Generated by" },
  impacts: { out: "Impacts", in: "Impacted by" },
};

/**
 * Edge types no panel line covers.
 *
 * `composes` only. A `composes` edge is half of a relationship whose other half
 * is `metadata.playlist.entries`; writing one without the other leaves the
 * flow's order to `journey-graph`'s "append the missing children" fallback,
 * which is a silent reorder nobody asked for. `PlaylistEditor` owns that write,
 * and the panel's read of it — the Invocation section — stays read-only for the
 * same reason.
 */
export const PANEL_EXCLUDED_EDGE_TYPES: readonly EdgeTypeId[] = ["composes"];

/**
 * The order lines appear in, as an explicit list.
 *
 * Not `EDGE_TYPE_IDS`' order: sorting by that enum's index would silently
 * reorder every panel the day an edge type is appended to it. Covers lines
 * first (the per-species spec order), then cross-layer, then decision links.
 */
export const RELATION_LINE_ORDER: readonly RelationLineId[] = [
  "covers:out",
  "covers:in",
  "calls:out",
  "calls:in",
  "displays:out",
  "displays:in",
  "queries:out",
  "queries:in",
  "supersedes:out",
  "supersedes:in",
  "generates:out",
  "generates:in",
  "impacts:out",
  "impacts:in",
];

/** The relation lines a node of this species has, in {@link RELATION_LINE_ORDER}. */
export function relationLinesFor(species: SpeciesId): RelationLineSpec[] {
  const lines: RelationLineSpec[] = [];

  for (const [edgeType, pairs] of Object.entries(VALID_EDGE_SEMANTICS) as [
    EdgeTypeId,
    ReadonlyArray<[SpeciesId, SpeciesId]>,
  ][]) {
    if (PANEL_EXCLUDED_EDGE_TYPES.includes(edgeType)) continue;

    for (const direction of ["out", "in"] as const) {
      const counterpartSpecies = [
        ...new Set(
          pairs
            .filter(([source, target]) => (direction === "out" ? source : target) === species)
            .map(([source, target]) => (direction === "out" ? target : source)),
        ),
      ];
      if (counterpartSpecies.length === 0) continue;

      lines.push({
        id: `${edgeType}:${direction}`,
        edgeType,
        direction,
        label: RELATION_LINE_LABELS[edgeType][direction],
        counterpartSpecies,
      });
    }
  }

  return lines.sort(
    (a, b) => RELATION_LINE_ORDER.indexOf(a.id) - RELATION_LINE_ORDER.indexOf(b.id),
  );
}

/** One row of a line: the counterpart's id, and the edge that put it there. */
export interface RelationRow {
  edgeId: string;
  counterpartId: string;
}

/**
 * The edges filling one line for one node, in edge order.
 *
 * Ids, not nodes: the caller resolves them and drops what this snapshot cannot
 * see, the same way `coveredAnchorsOf` does — a row naming an id the panel
 * cannot show is worse than no row.
 *
 * De-duplicated on the counterpart, keeping the first edge. `e-{source}-{target}`
 * makes a duplicate pair impossible to mint through the app, but a hand-edited
 * or half-synced bundle can carry two edges with the same endpoints and
 * different ids, and listing the same node twice is a bug a reader would report
 * as a data-loss scare.
 */
export function relationRows(
  nodeId: string,
  line: RelationLineSpec,
  edges: readonly Edge[],
): RelationRow[] {
  const rows = edges
    .filter((edge) => edge.edge_type === line.edgeType)
    .filter((edge) => (line.direction === "out" ? edge.source_id : edge.target_id) === nodeId)
    .map((edge) => ({
      edgeId: edge.id,
      counterpartId: line.direction === "out" ? edge.target_id : edge.source_id,
    }));

  return [...new Map(rows.map((row) => [row.counterpartId, row])).values()];
}
