#!/usr/bin/env node

/**
 * The panel's relation grammar (lib/utils/relation-lines.ts).
 *
 * The claim: the panel and the canvas connect dialog read ONE grammar. Every
 * assertion here is therefore written against `VALID_EDGE_SEMANTICS` rather
 * than against a hand-copied expectation, except the per-species snapshots —
 * which are hand-written on purpose, because they are the thing a reader of a
 * panel sees and a silent change to them is a UI regression this suite exists
 * to catch.
 */

const assert = require("node:assert/strict");
const { loadRelationLines } = require("./load-relation-lines");

const {
  relationLinesFor,
  relationRows,
  RELATION_LINE_ORDER,
  RELATION_LINE_LABELS,
  PANEL_EXCLUDED_EDGE_TYPES,
  VALID_EDGE_SEMANTICS,
  applyOps,
  SPECIES_IDS,
  // The write plans (lib/utils/node-relations.ts), asserted in § 8.
  planRelationLink,
  planRelationUnlink,
  planRelationNew,
} = loadRelationLines();

// Build-dir cleanup is the loader's job now (registered once inside
// `loadRelationLines()`), not this suite's — Part 3's second suite behind the
// same loader gets it by construction instead of having to copy a handler.

const labelsOf = (species) => relationLinesFor(species).map((line) => line.label);

// --- 1: the per-species snapshot -------------------------------------------

const SNAPSHOTTED_SPECIES = ["view", "flow", "data-model", "api-endpoint", "acceptance", "decision"];

// If a species is ever added to SPECIES_IDS without a snapshot here, this
// suite's per-species checks below would silently shrink to cover fewer
// species than the grammar has. Catch that here instead.
assert.deepEqual(
  [...SNAPSHOTTED_SPECIES].sort(),
  [...SPECIES_IDS].sort(),
  "the snapshot list covers every species — add one above when a species is added",
);

assert.deepEqual(labelsOf("view"), [
  "Acceptances", "Calls", "Called by", "Displays", "Impacted by",
], "a view's lines, in order");

assert.deepEqual(labelsOf("flow"), [
  "Acceptances", "Calls", "Impacted by",
], "a flow's lines, in order");

assert.deepEqual(labelsOf("data-model"), [
  "Displayed by", "Queried by", "Impacted by",
], "a data model's lines, in order");

assert.deepEqual(labelsOf("api-endpoint"), [
  "Calls", "Called by", "Queries", "Impacted by",
], "an api endpoint's lines, in order");

assert.deepEqual(labelsOf("acceptance"), [
  "Covers", "Generated by",
], "an acceptance's lines, in order");

assert.deepEqual(labelsOf("decision"), [
  "Supersedes", "Superseded by", "Generated acceptances", "Impacts",
], "a decision's lines, in order");

// --- 2: composes is excluded outright --------------------------------------

// A `composes` edge is half of a relationship whose other half is
// `metadata.playlist.entries`. Writing one without the other leaves the flow's
// order to journey-graph's "append the missing children" fallback, which is a
// silent reorder. PlaylistEditor owns that write.
assert.deepEqual([...PANEL_EXCLUDED_EDGE_TYPES], ["composes"]);
for (const species of SPECIES_IDS) {
  assert(
    relationLinesFor(species).every((line) => line.edgeType !== "composes"),
    `no composes line on a ${species}`,
  );
}

// --- 3: every line is the grammar's, not a restatement ----------------------

for (const species of SPECIES_IDS) {
  for (const line of relationLinesFor(species)) {
    const pairs = VALID_EDGE_SEMANTICS[line.edgeType];
    for (const counterpart of line.counterpartSpecies) {
      const [source, target] =
        line.direction === "out" ? [species, counterpart] : [counterpart, species];
      assert(
        pairs.some(([s, t]) => s === source && t === target),
        `${species} ${line.id} admits ${counterpart} per the grammar`,
      );
    }
    assert(line.counterpartSpecies.length > 0, `${species} ${line.id} has somewhere to point`);
    assert.equal(new Set(line.counterpartSpecies).size, line.counterpartSpecies.length,
      `${species} ${line.id} lists each counterpart species once`);
  }
}

// The converse: no admissible pair is missing a line. This is what catches an
// edge type added to the enum and forgotten here.
for (const [edgeType, pairs] of Object.entries(VALID_EDGE_SEMANTICS)) {
  if (PANEL_EXCLUDED_EDGE_TYPES.includes(edgeType)) continue;
  for (const [source, target] of pairs) {
    const out = relationLinesFor(source).find((line) => line.id === `${edgeType}:out`);
    assert(out && out.counterpartSpecies.includes(target),
      `${source} has an outbound ${edgeType} line reaching ${target}`);
    const inbound = relationLinesFor(target).find((line) => line.id === `${edgeType}:in`);
    assert(inbound && inbound.counterpartSpecies.includes(source),
      `${target} has an inbound ${edgeType} line reached from ${source}`);
  }
}

// --- 4: every edge type has both labels ------------------------------------

// Without this, appending an edge type to EDGE_TYPE_IDS renders `undefined` as
// a panel heading rather than failing anywhere.
for (const edgeType of Object.keys(VALID_EDGE_SEMANTICS)) {
  const labels = RELATION_LINE_LABELS[edgeType];
  assert(labels && labels.out && labels.in, `${edgeType} has an outbound and an inbound label`);
}

// --- 5: the order is explicit, not the enum's ------------------------------

// Sorting by EDGE_TYPE_IDS index would silently reorder every panel the day an
// edge type is appended to that enum, so the order is its own list — and every
// line a species can have must be in it. This is also what guards the "rank
// unranked ids last, not first" rule: `relationLinesFor` ranks a line id
// missing from RELATION_LINE_ORDER with `Number.MAX_SAFE_INTEGER` rather than
// `indexOf`'s -1, so an omission sorts to the bottom of the panel (visible,
// harmless) instead of the top (a silent regression that reads as the line
// the panel cares about most). There is no way to construct an unranked id
// today — every id `relationLinesFor` can produce is checked against the
// order right here — so that fallback path has no test of its own; this loop
// is the guard that would need to fail before it could ever run.
for (const species of SPECIES_IDS) {
  for (const line of relationLinesFor(species)) {
    assert(RELATION_LINE_ORDER.includes(line.id), `${line.id} has a place in the order`);
  }
}
assert.equal(new Set(RELATION_LINE_ORDER).size, RELATION_LINE_ORDER.length,
  "no line id appears twice in the order");

// --- 6: relationLinesFor("nope") --------------------------------------------

assert.deepEqual(relationLinesFor("nope"), [], "an unknown species has no lines, not a throw");

// --- 6b: the table is frozen at every level ---------------------------------

// A shallow freeze on the per-species array would leave the spec objects
// inside it mutable — and because the table is built once at module load and
// handed out to every caller, a mutation through one caller would corrupt
// every other caller's view for the rest of the process, not just its own
// throwaway array.
{
  const [firstLine] = relationLinesFor("view");
  assert(Object.isFrozen(firstLine), "a line spec is frozen, not just the array holding it");
  assert(Object.isFrozen(firstLine.counterpartSpecies), "a spec's counterpartSpecies array is frozen");

  const originalLabel = firstLine.label;
  assert.throws(() => {
    "use strict";
    firstLine.label = "PWNED";
  }, "mutating a frozen spec throws in strict mode");
  // Non-strict assignment to a frozen object's property is a silent no-op
  // rather than a throw, so this is the assertion that actually matters: the
  // mutation attempt above must not have stuck, and the next caller must see
  // the same object the first caller did.
  assert.equal(relationLinesFor("view")[0].label, originalLabel,
    "a mutation attempt does not leak into the next caller");
}

// --- 7: relationRows reads the edges the line names -------------------------

const PROJECT = "p1";
const edge = (source, target, edge_type, id) => ({
  id: id ?? `e-${source}-${target}`,
  project_id: PROJECT,
  source_id: source,
  target_id: target,
  edge_type,
});

const viewLines = relationLinesFor("view");
const calls = viewLines.find((line) => line.id === "calls:out");
const calledBy = viewLines.find((line) => line.id === "calls:in");

const world = [
  edge("V-home", "API-orders", "calls"),
  edge("API-push", "V-home", "calls"),
  edge("V-home", "DM-user", "displays"),
  edge("V-other", "API-orders", "calls"),
];

assert.deepEqual(
  relationRows("V-home", calls, world).map((row) => row.counterpartId),
  ["API-orders"],
  "an outbound line reads edges leaving this node",
);
assert.deepEqual(
  relationRows("V-home", calledBy, world).map((row) => row.counterpartId),
  ["API-push"],
  "an inbound line reads edges arriving at it — the same edge type, the other direction",
);
assert.deepEqual(
  relationRows("V-home", calls, world)[0].edgeId,
  "e-V-home-API-orders",
  "the row carries its edge id",
);

// Rows come back in edge order, not sorted or reversed. Every assertion above
// yields a single row, which a stray `.sort()`/`.reverse()` would still pass.
assert.deepEqual(
  relationRows("V-home", calls, [
    edge("V-home", "API-z", "calls"),
    edge("V-home", "API-b", "calls"),
  ]).map((row) => row.counterpartId),
  ["API-z", "API-b"],
  "rows come back in edge order, not sorted",
);

// A hand-edited bundle can hold two edges with the same endpoints and different
// ids. Listing the counterpart twice would read as data loss to the user.
assert.equal(
  relationRows("V-home", calls, [
    edge("V-home", "API-orders", "calls"),
    edge("V-home", "API-orders", "calls", "e-duplicate"),
  ]).length,
  1,
  "a duplicated pair is one row",
);

// The row that survives is the FIRST edge — the canonical id, stable under a
// re-sync — not whichever one happened to be written last into the Map.
assert.equal(
  relationRows("V-home", calls, [
    edge("V-home", "API-orders", "calls", "e-canonical"),
    edge("V-home", "API-orders", "calls", "e-stray"),
  ])[0].edgeId,
  "e-canonical",
  "a duplicated pair keeps the first edge — the canonical id, stable under a re-sync",
);

assert.deepEqual(relationRows("V-home", calls, []), [], "no edges, no rows");

// A self-loop (api-endpoint → api-endpoint, decision → decision) is real graph
// data, not filtered: it shows up as one row under the node's outbound line
// and one row under its inbound line, same as any edge between two nodes.
const apiLines = relationLinesFor("api-endpoint");
const apiCalls = apiLines.find((line) => line.id === "calls:out");
const apiCalledBy = apiLines.find((line) => line.id === "calls:in");
const selfLoop = [edge("API-a", "API-a", "calls")];
assert.deepEqual(
  relationRows("API-a", apiCalls, selfLoop).map((row) => row.counterpartId),
  ["API-a"],
  "a self-loop renders under the outbound line",
);
assert.deepEqual(
  relationRows("API-a", apiCalledBy, selfLoop).map((row) => row.counterpartId),
  ["API-a"],
  "and under the inbound line — the same edge, read from the other direction",
);

// --- 8: the write plans -----------------------------------------------------

// `planRelation*` and `applyOps` come from the destructure at the top of this
// file — a second `loadRelationLines()` here would wipe and rebuild the build
// directory under the modules already required from it.

const n = (id, species, extra = {}) => ({
  id, project_id: PROJECT, species, title: id, status: "idea", platforms: [], ...extra,
});

const V = n("V-home", "view");
const API = n("API-orders", "api-endpoint");
const DEC = n("DEC-vendor", "decision");

// Outbound: the edge leaves the panel's node.
assert.deepEqual(planRelationLink(V, API, calls, PROJECT, []), [
  {
    op: "create_edge",
    edge: {
      id: "e-V-home-API-orders",
      project_id: PROJECT,
      source_id: "V-home",
      target_id: "API-orders",
      edge_type: "calls",
    },
  },
]);

// Inbound: the SAME line kind, the endpoints swapped. Getting this backwards
// writes an edge the importer rejects, so it is asserted rather than assumed.
assert.deepEqual(
  planRelationLink(V, API, calledBy, PROJECT, []).map((op) => [op.edge.source_id, op.edge.target_id]),
  [["API-orders", "V-home"]],
);

// The grammar is the authority, here as on the canvas. A decision does not
// `calls` anything, and a plan that emitted it would be an `edge-semantics`
// error on the next import.
assert.throws(
  () => planRelationLink(V, DEC, calls, PROJECT, []),
  /edge-semantics|grammar/i,
  "an edge the grammar forbids is refused, not written",
);

// Two no-ops that are not errors: already linked, and pointed at itself.
assert.deepEqual(
  planRelationLink(V, API, calls, PROJECT, [edge("V-home", "API-orders", "calls")]),
  [],
  "already linked is a no-op",
);
assert.deepEqual(planRelationLink(V, V, calls, PROJECT, []), [], "a node cannot relate to itself");

// Unlink deletes EVERY matching edge, not the first — a hand-edited bundle can
// carry two with the same endpoints, and deleting one leaves the row on screen
// after the user removed it, with no way to tell why.
assert.deepEqual(
  planRelationUnlink("V-home", "API-orders", calls, [
    edge("V-home", "API-orders", "calls"),
    edge("V-home", "API-orders", "calls", "e-duplicate"),
    edge("V-home", "DM-user", "displays"),
  ]).map((op) => op.edge_id),
  ["e-V-home-API-orders", "e-duplicate"],
);

// The inbound direction unlinks the same edge read the other way round: the
// `calls:in` line of API-orders names V-home, and removing that row must
// delete the V-home → API-orders edge.
assert.deepEqual(
  planRelationUnlink("API-orders", "V-home", calledBy, [
    edge("V-home", "API-orders", "calls"),
  ]).map((op) => op.edge_id),
  ["e-V-home-API-orders"],
);

// linkNew mints the node and the edge as one batch.
const plan = planRelationNew(V, calls, "api-endpoint", "POST /refunds", PROJECT, [], new Map([["V-home", V]]));
assert.equal(plan.node.species, "api-endpoint");
assert.equal(plan.node.title, "POST /refunds");
assert.equal(plan.node.status, "idea");
assert.deepEqual(plan.node.platforms, [], "a node minted mid-gesture claims no platform it was not asked about");
assert.equal(plan.ops.length, 2, "the node and its edge commit together");
assert.equal(plan.ops[0].op, "create_node");
assert.equal(plan.ops[1].op, "create_edge");

// A whitespace title is a mis-click, not an intent to mint a hash-suffixed id.
assert.equal(planRelationNew(V, calls, "api-endpoint", "   ", PROJECT, [], new Map()), null);

// The plan is judged by the graph it produces, through the real interpreter.
{
  const applied = applyOps({ nodes: [V], edges: [] }, plan.ops);
  assert.equal(applied.nodes.length, 2);
  assert.equal(applied.edges.length, 1);
  assert.equal(applied.edges[0].source_id, "V-home");
  assert.equal(applied.edges[0].target_id, plan.node.id);
}

console.log("relation-lines: ok");
