#!/usr/bin/env node

/**
 * The panel's relation grammar (lib/utils/relation-lines.ts).
 *
 * The claim: the panel and the canvas connect dialog read ONE grammar. Every
 * assertion here is therefore written against `VALID_EDGE_SEMANTICS` rather
 * than against a hand-copied expectation, except the per-species snapshots —
 * which are hand-written on purpose, because they are the thing a reader of a
 * panel sees and a silent change to them is a UI regression this suite exists
 * to catch.
 */

const assert = require("node:assert/strict");
const fs = require("fs");
const { loadRelationLines, BUILD_DIR } = require("./load-relation-lines");

const {
  relationLinesFor,
  relationRows,
  RELATION_LINE_ORDER,
  RELATION_LINE_LABELS,
  PANEL_EXCLUDED_EDGE_TYPES,
  VALID_EDGE_SEMANTICS,
  applyOps,
  // Added in part 3 — absent until then, which is fine: § 7 is added in the
  // same task that creates them.
  planRelationLink,
  planRelationUnlink,
  planRelationNew,
} = loadRelationLines();

const labelsOf = (species) => relationLinesFor(species).map((line) => line.label);

// --- 1: the per-species snapshot -------------------------------------------

assert.deepEqual(labelsOf("view"), [
  "Acceptances", "Calls", "Called by", "Displays", "Impacted by",
], "a view's lines, in order");

assert.deepEqual(labelsOf("flow"), [
  "Acceptances", "Calls", "Impacted by",
], "a flow's lines, in order");

assert.deepEqual(labelsOf("data-model"), [
  "Displayed by", "Queried by", "Impacted by",
], "a data model's lines, in order");

assert.deepEqual(labelsOf("api-endpoint"), [
  "Calls", "Called by", "Queries", "Impacted by",
], "an api endpoint's lines, in order");

assert.deepEqual(labelsOf("acceptance"), [
  "Covers", "Generated by",
], "an acceptance's lines, in order");

assert.deepEqual(labelsOf("decision"), [
  "Supersedes", "Superseded by", "Generated acceptances", "Impacts",
], "a decision's lines, in order");

// --- 2: composes is excluded outright --------------------------------------

// A `composes` edge is half of a relationship whose other half is
// `metadata.playlist.entries`. Writing one without the other leaves the flow's
// order to journey-graph's "append the missing children" fallback, which is a
// silent reorder. PlaylistEditor owns that write.
assert.deepEqual([...PANEL_EXCLUDED_EDGE_TYPES], ["composes"]);
for (const species of ["view", "flow", "data-model", "api-endpoint", "acceptance", "decision"]) {
  assert(
    relationLinesFor(species).every((line) => line.edgeType !== "composes"),
    `no composes line on a ${species}`,
  );
}

// --- 3: every line is the grammar's, not a restatement ----------------------

for (const species of ["view", "flow", "data-model", "api-endpoint", "acceptance", "decision"]) {
  for (const line of relationLinesFor(species)) {
    const pairs = VALID_EDGE_SEMANTICS[line.edgeType];
    for (const counterpart of line.counterpartSpecies) {
      const [source, target] =
        line.direction === "out" ? [species, counterpart] : [counterpart, species];
      assert(
        pairs.some(([s, t]) => s === source && t === target),
        `${species} ${line.id} admits ${counterpart} per the grammar`,
      );
    }
    assert(line.counterpartSpecies.length > 0, `${species} ${line.id} has somewhere to point`);
    assert.equal(new Set(line.counterpartSpecies).size, line.counterpartSpecies.length,
      `${species} ${line.id} lists each counterpart species once`);
  }
}

// The converse: no admissible pair is missing a line. This is what catches an
// edge type added to the enum and forgotten here.
for (const [edgeType, pairs] of Object.entries(VALID_EDGE_SEMANTICS)) {
  if (PANEL_EXCLUDED_EDGE_TYPES.includes(edgeType)) continue;
  for (const [source, target] of pairs) {
    const out = relationLinesFor(source).find((line) => line.id === `${edgeType}:out`);
    assert(out && out.counterpartSpecies.includes(target),
      `${source} has an outbound ${edgeType} line reaching ${target}`);
    const inbound = relationLinesFor(target).find((line) => line.id === `${edgeType}:in`);
    assert(inbound && inbound.counterpartSpecies.includes(source),
      `${target} has an inbound ${edgeType} line reached from ${source}`);
  }
}

// --- 4: every edge type has both labels ------------------------------------

// Without this, appending an edge type to EDGE_TYPE_IDS renders `undefined` as
// a panel heading rather than failing anywhere.
for (const edgeType of Object.keys(VALID_EDGE_SEMANTICS)) {
  const labels = RELATION_LINE_LABELS[edgeType];
  assert(labels && labels.out && labels.in, `${edgeType} has an outbound and an inbound label`);
}

// --- 5: the order is explicit, not the enum's ------------------------------

// Sorting by EDGE_TYPE_IDS index would silently reorder every panel the day an
// edge type is appended to that enum, so the order is its own list — and every
// line a species can have must be in it.
for (const species of ["view", "flow", "data-model", "api-endpoint", "acceptance", "decision"]) {
  for (const line of relationLinesFor(species)) {
    assert(RELATION_LINE_ORDER.includes(line.id), `${line.id} has a place in the order`);
  }
}
assert.equal(new Set(RELATION_LINE_ORDER).size, RELATION_LINE_ORDER.length,
  "no line id appears twice in the order");

// --- 6: relationRows reads the edges the line names -------------------------

const PROJECT = "p1";
const edge = (source, target, edge_type, id) => ({
  id: id ?? `e-${source}-${target}`,
  project_id: PROJECT,
  source_id: source,
  target_id: target,
  edge_type,
});

const viewLines = relationLinesFor("view");
const calls = viewLines.find((line) => line.id === "calls:out");
const calledBy = viewLines.find((line) => line.id === "calls:in");

const world = [
  edge("V-home", "API-orders", "calls"),
  edge("API-push", "V-home", "calls"),
  edge("V-home", "DM-user", "displays"),
  edge("V-other", "API-orders", "calls"),
];

assert.deepEqual(
  relationRows("V-home", calls, world).map((row) => row.counterpartId),
  ["API-orders"],
  "an outbound line reads edges leaving this node",
);
assert.deepEqual(
  relationRows("V-home", calledBy, world).map((row) => row.counterpartId),
  ["API-push"],
  "an inbound line reads edges arriving at it — the same edge type, the other direction",
);
assert.deepEqual(
  relationRows("V-home", calls, world)[0].edgeId,
  "e-V-home-API-orders",
  "the row carries its edge id",
);

// A hand-edited bundle can hold two edges with the same endpoints and different
// ids. Listing the counterpart twice would read as data loss to the user.
assert.equal(
  relationRows("V-home", calls, [
    edge("V-home", "API-orders", "calls"),
    edge("V-home", "API-orders", "calls", "e-duplicate"),
  ]).length,
  1,
  "a duplicated pair is one row",
);

assert.deepEqual(relationRows("V-home", calls, []), [], "no edges, no rows");

console.log("relation-lines: ok");
fs.rmSync(BUILD_DIR, { recursive: true, force: true });
